[project]
authors = ["jnswkz <23520408@gm.uit.edu.vn>"]
channels = ["conda-forge"]
description = "Small crawler for GPU and CPU information from TPU" 
name = "gpu_cpu_crawler"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
gpucrawl = "python gpucrawl.py"
cpucrawl = "python cpucrawl.py"

[dependencies]
beautifulsoup4 = ">=4.9.3"
pandas = ">=1.2.4"
aiohttp = ">=3.7.4"
dateparser = ">=1.0.0"
natsort = ">=8.4.0,<9"
